name: bluesky-seed-service
host: 
tags:
  - seed

user_token_trusted: false

rest:
  port: 8081
  context: /
  health_check_path: /health_check

consul:
  host: localhost
  port: 8500
  service:
    check:
      interval: 30s
      timeout: 1m
      deregister_critical_service_after: 30s
  client:
    check:
      internval: 30s

cassandra:
  hosts:
    - 172.16.15.63
  port: 9042
  keyspace: bluesky_seed

kafka:
  hosts:
    - 172.16.15.63:9092

log:
  host: 172.16.15.63
  port: 24224

bluesky-auth-service:
  protocol: http
  consul: true
  servers:
    - 172.16.15.63

bluesky-notification-service:
  protocol: http
  consul: true
  servers:
    - 172.16.15.63
