export enum ApplicationStatus {
    OK = "OK",
    INVALID_API_KEY = "INVALID_API_KEY",
    INVALID_USER_TOKEN = "INVALID_USER_TOKEN",
    PERMISSION_DENIED = "PERMISSION_DENIED",
    ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND",
    INVALID_ARGUMENT = "INVALID_ARGUMENT",
    EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND",
    INCORRECT_PASSWORD = "INCORRECT_PASSWORD",
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
    EMAIL_UNIQUE = "EMAIL_UNIQUE",
    PHONE_UNIQUE = "PHONE_UNIQUE",
    INTERNAL_ERROR = "INTERNAL_ERROR"
}