name: bluesky-seed-service
host: localhost
tags:
  - seed

rest:
  port: 8080
  context: /
  health_check_path: /health_check

consul:
  host: localhost
  port: 8500
  service:
    check:
      interval: 30s
      timeout: 1m
      deregister_critical_service_after: 30s
  client:
    check:
      internval: 30s

cassandra:
  hosts:
    - 172.16.15.64
  port: 9042
  keyspace: bluesky_seed

log:
  host: localhost
  port: 24224